[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings=["@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts"] # this is used to replace @chainlink/contracts/ with the expression that it is equal to here
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
